### PR TITLE
New default tolerance suggestions

### PR DESCRIPTION
**Pull request by briancoley**
Changed some default tolerance dimensions.

Added lipOverhangTolerance value.

Added notchToTable option.

Added shapeOnSide option.

Fixed the horrendous lies put in by the previous coder.

### CODE REVIEW

**Comment by briancoley** [comment]
Is this done yet? What the heck?

**Comment by mtabije** [comment]
Tolerance is for the weak minded.

**Review by mtabije — CHANGES_REQUESTED** [review]
Please add a boolean variable to Testing called 
clipSidePrint

**Comment by briancoley** [comment]
I've made the requested change.

**Review by mtabije — APPROVED** [review]

**Pull request merged**
